### ISSUE TITLE
Maintain the Geolocation API Specification

### ISSUE THREAD

**Issue by xfq** [w3c/das-charter#76] opened 2019-01-23 04:09 UTC
The spec still needs some maintenance work, such as restrictions in non-secure contexts.

Should this group take it, given its work on the Geolocation Sensor?

**Comment by anssiko** [comment] 2019-01-23 12:24
@xfq, thanks, I hope we are able to add Geolocation API spec maintenance in scope without going through the costly rechartering process given the Geolocation API technical scope is already captured in that of the Geolocation Sensor.

If we can take this light-weight route, how to kick off the process for doing so, amend the charter text etc.? Thanks for your help.

**Comment by wseltzer** [comment] 2019-01-25 21:12
@anssiko where is Geolocation Sensor? 

The issue is that the current charter is explicitly scoped-down by the language of [3.2](https://www.w3.org/2016/03/device-sensors-wg-charter.html#scope) "If additional in-scope Recommendation-track deliverables need to be added to the Charter before the Charter expires, the Working Group will prepare an updated Charter that differs only in deliverables. In the interest of agile spec development, the group requests that the Advisory Committee and Director restrict approval reviews for those Charter deliverables adjustments to just the changes in the Charter, rather than considering the entire Charter again for review." 

I'd propose to ask W3M and the AC for the narrow review described here: i.e., "just review the new deliverable."

**Comment by anssiko** [comment] 2019-01-25 21:18
>@anssiko where is Geolocation Sensor?

@wseltzer https://w3c.github.io/geolocation-sensor/

**Comment by anssiko** [comment] 2019-01-25 21:21
Also, the proposed plan sounds good to me. Does staff take an appropriate action?

Also loop in DAS WG co-chair @reillyeon.

**Comment by wseltzer** [comment] 2019-01-25 21:22
Ah thanks, I was looking at the wrong version of the charter, current charter is 
https://www.w3.org/2018/06/devices-sensors-wg-charter.html

Yes, I'll start the W3M review.

**Comment by anssiko** [comment] 2019-01-28 11:02
@wseltzer, thanks for the swift response and taking an action. I assume this issue is notified when there's a resolution.

**Comment by plehegar** [comment] 2019-02-04 21:48
Addressed by #77

**Closed as completed** 2019-02-12 15:13 UTC
